server:
  port: 8088
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/yun6?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: C:/tmp/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1